#!/usr/bin/env sh
if pgrep -f "joycond" ;
    then
        kitty -e sudo systemctl stop joycond.service && notify-send 'joycond disabled ';
    else 
        kitty -e sudo systemctl start joycond.service && notify-send 'joycond enabled';
fi